### ISSUE TITLE
Dont work the game in the section 6.5 base code

### ISSUE THREAD

**Issue by carlosgub** [thedrlambda/five-lines#4]
When I finish the 6.4 section did'nt work the game or if the I copy the 6.5 base code is the same result. I don't knwo if you can help me :D

<img width="277" alt="image" src="https://user-images.githubusercontent.com/30916886/87568658-9faeac80-c68b-11ea-820d-c42eaf9a5b97.png">

**Comment by thedrlambda** [comment]
Hi Carlos, it turns out that some reordering is required, due to the way Typescript initializes things. I will fix the history. In the meantime, you can move the RemoveStrategies, and KeyConfiguration (including constants) up to the top of the file, should fix this error. 
Then I also discovered that the `gameLoop` needs a small update, the last line should be:
setTimeout(() => gameLoop(map), sleep).

Thanks for being so thorough, and thanks for letting me know!

**Comment by carlosgub** [comment]
Hi @maxipaxi, with your steps it work the game again :). Thanks. If you want close this issue.
One question, the game is like Supaplex game of the 90's ?

**Comment by thedrlambda** [comment]
It is yes, I think there has been many implementations. My first experience with it was a game on miniclip called "Aqua Energizer". :)

**Comment by carlosgub** [comment]
Miniclip, i forget that page for play mini games online. I never play that game. Cheers
